#!/usr/bin/env python3
"""pack_ui.py - pack ui/ into a C array table the firmware serves from flash.

Run after every UI edit:

    python tools/pack_ui.py

Writes components/van_ui/van_ui_html.h. The generated header is committed on
purpose: an ESPHome build must never depend on a Python step the build machine
might skip, and a firmware whose UI silently did not update is a bad afternoon.
The component compares the hash below against the sources at codegen time and
fails the build if you forgot to run this.

Four assets, three of which exist only so the page can be launched from a home
screen icon instead of by typing an IP (see docs/decisions.md):

    index.html          the app
    portal.html         what the phone's connectivity probe gets
    manifest.webmanifest
    icon.png            generated by tools/make_icon.py

Stdlib only.
"""

import gzip
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "ui"
OUT = ROOT / "components" / "van_ui" / "van_ui_html.h"

# (source file, C symbol stem, MIME type, gzip?)
#
# The PNG is stored raw: it is already deflate-compressed internally, so a
# second pass costs flash and buys nothing, and serving it without the
# Content-Encoding header keeps the handler's response path uniform.
ASSETS = [
    ("index.html",          "INDEX",    "text/html",             True),
    ("portal.html",         "PORTAL",   "text/html",             True),
    ("manifest.webmanifest", "MANIFEST", "application/manifest+json", True),
    ("icon.png",            "ICON",     "image/png",             False),
]

# Flash is 16MB, so size is not a constraint - but a page this size on a node
# that must not starve its BLE task is, so keep an eye on it.
WARN_BYTES = 48 * 1024


def emit_array(lines, symbol, blob):
    lines.append(f"const size_t VAN_UI_{symbol}_LEN = {len(blob)};")
    lines.append(f"const uint8_t VAN_UI_{symbol}[] = {{")
    for i in range(0, len(blob), 16):
        lines.append("    " + "".join(f"0x{b:02x}," for b in blob[i:i + 16]))
    lines.append("};")
    lines.append("")


def main() -> int:
    missing = [name for name, *_ in ASSETS if not (SRC_DIR / name).is_file()]
    if missing:
        print(f"ERROR: missing in ui/: {', '.join(missing)}", file=sys.stderr)
        if "icon.png" in missing:
            print("Run:  python tools/make_icon.py", file=sys.stderr)
        return 1

    # One hash over every source, in table order, with names included so a
    # rename is a change too. This is the staleness marker __init__.py checks.
    h = hashlib.sha256()
    body, report, total = [], [], 0

    for name, symbol, _mime, do_gzip in ASSETS:
        raw = (SRC_DIR / name).read_bytes()
        h.update(name.encode())
        h.update(raw)
        # mtime=0 so the output is byte-identical for identical input: a
        # rebuild with no UI change must not show up as a diff.
        blob = gzip.compress(raw, compresslevel=9, mtime=0) if do_gzip else raw
        emit_array(body, symbol, blob)
        total += len(blob)
        report.append((name, len(raw), len(blob), do_gzip))

    digest = h.hexdigest()
    lines = [
        "// GENERATED by tools/pack_ui.py - do not edit.",
        "// Sources: " + ", ".join(f"ui/{n}" for n, *_ in ASSETS),
        f"// {total} bytes of flash in total.",
        f'#define VAN_UI_SHA256 "{digest}"',
        "",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace esphome {",
        "namespace van_ui {",
        "",
    ]
    lines += body
    lines += ["}  // namespace van_ui", "}  // namespace esphome", ""]

    OUT.write_text("\n".join(lines), encoding="utf-8")

    for name, raw_len, blob_len, do_gzip in report:
        how = f"-> {blob_len} B gzip" if do_gzip else "raw"
        print(f"  {name:22} {raw_len:6} B {how}")
    print(f"{total} B total -> {OUT.relative_to(ROOT)}")
    if total > WARN_BYTES:
        print(f"WARNING: {total} B exceeds the {WARN_BYTES} B soft limit.",
              file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
